version: "3.5"
services:
  elasticsearch:
    container_name: temporal-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms100m -Xmx100m
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
    networks:
      - temporal-network
  kafka:
    container_name: temporal-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - 9092:9092
    networks:
      - temporal-network
  mysql:
    container_name: temporal-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - temporal-network
  temporal:
    container_name: temporal
    depends_on:
      - mysql
      - elasticsearch
      - kafka
    environment:
      - DB=mysql
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_es.yaml
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
      - KAFKA_SEEDS=kafka
    image: temporalio/auto-setup:1.5.1
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - temporal-network
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.5.1
    stdin_open: true
    tty: true
    networks:
      - temporal-network
  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
    image: temporalio/web:1.4.1
    ports:
      - 8088:8088
    networks:
      - temporal-network
  zookeeper:
    container_name: temporal-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
    networks:
      - temporal-network
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
