apiVersion: 1

datasources:
  - name: 'Temporal Prometheus'
    type: 'prometheus'
    orgId: 1
    url: 'http://prometheus:9090'
    isDefault: true
    version: 1
    editable: true
  - name: 'Loki'
    type: loki
    access: proxy
    url: 'http://loki:3100'
    jsonData:
      maxLines: 1000
